### ISSUE TITLE
Mission statement

### ISSUE THREAD

**Issue by Gnomadicliving** [azeemh/gnomadic#3]
Mission & Bylaws Draft
Core Values

Gnomes are green 
and they are not mean
To each other
Or earth, our mother

Definitions-
Gnoom- A unique community that decides it's own rules 
under contract with Gnomadic to be green and be cool

Nomad- A person who wants to go into a gnoom, 
who signs a contract agreeing to be green and be cool

Donsy- A gnoom project in progress with multiple gnomes, 
working to improve the state of their home

Gnome- A nomad, once donsy aligned, who contributes to donsy plans and designs

Owl- A gnome found to be very wise, 
who knows how to be fair and did naturally rise

Green- Good to the earth and to the air.  For the waters, animals, plants, gnomies always care

Cool- Not aggressive toward gnomes, nomads, sisters or brothers.  
No force, no fraud, no coercion of others.

Community

Gnomes come from afar to build a network of gnooms
With many donsies, they have much to do
Gnomies love their gnooms and joining together
In gardens, woods, fishing and in all sorts of weather
Gnomies in gnooms get along well 
with spiritual flow and funny stories to tell
Witty, and smart, such good company
A gnoom full of gnomes you must see to believe 

Homelessness

Gnomies move about, day after day
It truly is the nomad way
But sometimes a gnome will look and see
A nomad with nowhere to be 
It makes gnomes sad to see the pain
To see nomads out in the snow and the rain
So gnomies team up and they build up the gnooms
So unsheltered nomads have free food and a room

Gnome Decision-Making Structure

Any nomad can choose to become a gnome
And join a gnoom, a safe warm home
They agree to be nice to people and land
From there they choose how to give a hand

And many hands a donsy makes
To connect and share for project sake
But an active donsy shouldn't be disturbed for creative process can be easily curbed
And gnomes get grumpy, so to avoid all of that
New gnomes get added once they learn all the facts
And agree to attend any donsies they choose
Often enough to stay up on the news

And from each donsy naturally arise, 
a group of owls, who have shown to be wise
Who make the call when there's a stall
So ultimately donsies get to the prize

Sustainable Agriculture

Gnomes sustain from what they grow on their land, 
and bring to local markets excess when they can
They use many methods for growing green,
integrating 'ponics and permaculture means.

Utility Sustainability

Gnomies they like their web3 and their tech, 
so energy needs must always be met
To be green, gnomes tap from many sources, 
like solar, hydro electric, and even manure from horses

Social Services

Many hurt nomads need a lot of care, 
so kind hearted gnomies are trained to be there, 
to counsel, advise, educate and to train, and help nomads get on their feet again, and using gamified strategies to promote social good, 
gnomies encourage all to give as they should

Land Development

Gnomes are eco-friendly in design of their homes 
using eco-conscious methods to build structures and domes.  
They re-invigorate both urban and rural spaces 
by growing food in normal and unusual places.

Farmer Inclusion

Farmers are very good friends of the gnomes 
and many desire to share their homes
To become the gnooms, and be cool and green
And Gnomes help with donsies they may never have seen
Like permaculture, soil conservation, 
or new ways of doing irrigation

Web 3
Gnomes have a website so log-in and see
It's where homesteaders and nomads connect to meet
Profiles share what they want to give 
in land, money, time, labor, expertise and/or skills
From there everyone does formally agree 
that they will be green and cool, you see
Because gnomes aren't mean, they're good to all, 
to black, white, rich, poor, big, or small
And to mother earth, they are so kind
So continuing through the site you'll find
Ways to help your neighbors and the land
Opportunities to chip in and give a hand
As you do your Quests and good deeds,
you'll be rewarded with money, crypto, NFTs
or goods, or services, whatever is fair
And the site will also help get things you need there
If you have a need as Maslow described
Enter it into the site's gnomie mind
and Quests will be made to suit your needs
And nomads and gnomies will likely see
and gnombassadors might give a hand, 
gnoom volunteers learning on the land
As apprentices they can learn a trade
Advancing with each ability made
Badges mean you get extra cred
As someone who has advanced ahead
And can teach to others what you know
So moving forward you both grow
But that's not all, so don't you fear
Another level exists here 
where gnomes, they play in AR space 
with a mission to save this world, this place
It's really complex this gnomie site
But we think that it works alright

Future Plans

Mobile donsies we plan to see, 
with markets and kitchens where nomads and gnomes eat free
expanded by further mobile designs, like haircare, dog training and the healing aligned.

Gnomies also like to green 
in places previously unseen 
Replacing lawns with plants to eat
And seeding spots along the streets
Growing upward, solar, polyculture...

Gnomadics's goal is to love people and the earth, our mother

**Comment by azeemh** [comment]
added
